# Generated by Django 4.0.8 on 2022-11-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=300)),
                ('imagen', models.ImageField(blank=True, upload_to='imagenes')),
                ('musica', models.FileField(blank=True, max_length=250, upload_to='mp3')),
            ],
        ),
    ]
